
title: "data wrangling"---
output: html_document
---


```{r}

library(tidyverse)  # install.packages('tidyverse')


```


```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')


# inspect the data
gapminder  # looks at all the data
head(gapminder)
tail(gapminder,10)  # default is 6

head(gapminder,3)

# summary statistics
str(gapminder)
summary(gapminder)
install.packages('skimr')
skimr::skim(gapminder)

names(gapminder)
dim(gapminder)
ncol(gapminder)

# reverse-engineer dim
c(nrow(gapminder),ncol(gapminder))
```
## Dplyr!


```{r}

#filter by rows


filter( gapminder, country=='Mexico')

filter( gapminder, country %in% c('Mexico','Peru','Brazil'),
        
        filter(gapminder,country=='Mexico', year==2002),
        
        
        ## find mean lifeExp of Sweden
        
        Sweden=filter(gapminder,country=='Sweden'),
        
        mean(Sweden$lifeExp)
        
        
        ## select by columns
        select(gapminder,year,lifeExp)
        
        select(gapminder,-continent,-lifeExp)  # exclude tese columns
        
        # use select and filter togethere
        
        gap_cambodia<-filter(gapminder,country=='Cambodia')
        gap_cambodia2<- select(gap_cambodia,-continent,lifeExp )
        
        
        ```
        
        
        The pipe operator will chagne
        ```{r}
        gapminder%>% head(3)  # thisi is =
        head(gapminder,3)
        
        
        # show this with pipes
        
        gap_cambodia<-filter(gapminder,country=='Cambodia')
        gap_cambodia2<- select(gap_cambodia,-continent,lifeExp )
        
        
        gap_cambodia<-gapminder %>% 
          filter(country=='Cambodia')  %>% 
          select(-continent,-lifeExp)
        
```



```{r}
# mutate adds new baribles
gapminder %>%
  mutate(index=1:nrow(gapminder))

gapminder %>%
  mutate(gdp=pop*gdpPercap)

## cahgenelenge:
#find the maximum gdpPErcap of Egypt and Viewtnam creat a new cololumn

 #use select and filter togethere


# #techered

gapminder %>%
  filter (country %in% c ('Egypt','Vietname')) %>%
  mutate(ddp=pop*gdpPercap) %>%
  mutate(max_gdp=max(fdp))

```


## 'group_by()'
```{r}
gap_gouped <- gapminder %>%
group_by(country) %>%
    mutate(gdp=pop*gdpPercap,
           max_gdp=max(gdp)) %>%
  ungroup()

## with summarize() or summarise()

gap_summarised <- gapminder %>%
  group_by(country)  %>%
  mutate(gdp=pop*gdpPercap) %>%
  summarise(max_gdp=max(gdp)) %>%
  ungroup()
```


## 'arrange()'
```{r}
gap_summarised <- gapminder %>%
  group_by(country)  %>%
  mutate(gdp=pop*gdpPercap) %>%
  summarise(max_gdp=max(gdp)) %>%
  ungroup()  %>%
  arrange(desc(max_gdp))


```







